version: "3.7"

services:
  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379

  celery:
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    restart: always
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./:/opt/app

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db

  telegram:
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    restart: always
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./:/opt/app
    command: ['poetry', 'run', 'python', '-m', 'bot']
