version: "3.7"

services:
  redis:
    image: redis:5-alpine
    restart: always

  app:
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    restart: always
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./:/opt/app

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  bot:
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    restart: always
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./:/opt/app
    command: ['poetry', 'run', 'python', '-m', 'bot']
