version: "3.7"

services:
  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379

  celery:
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    restart: always
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./:/opt/app

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/storage

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  telegram:
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    restart: always
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./:/opt/app
    command: ['poetry', 'run', 'python', '-m', 'bot']
